# Домашнее задание по третьей неделе
## С cs.mipt.ru
1. Создайте произвольный текстовый файл с несколькими строками произвольного текста.
Выведите в консоль строки файла, удалив лишние пробелы в начале и конце строк, если они есть (`strip`).
2. Запишите в новый файл содержимое списка строк (каждую строку с новой строки) без использования цикла.
В итоге должна получиться функция:
```python
def write_array(array, file_name):
    """записывает строки из array в файл file_name"""
    #ваш код здесь
    pass
```
3. Вам дана в [архиве](http://cs.mipt.ru/advanced_python/extra/lab3/main.zip) файловая структура, состоящая из директорий и файлов.
Необходимо распаковать этот архив **средствами языка python**, и затем найти в данной в файловой структуре все директории, в которых есть хотя бы один файл с расширением ".py".
Ответом на данную задачу будет являться файл со списком таких директорий, отсортированных в **лексикографическом порядке**.

## Не из cs.mipt
4. Загрузить `1.json` из папки w3/ и открыть его в питоне.
Добавить внутрь "GlossEntry" свойство {"week": 3} и сохранить результат в файл `1.json` двумя способами:
    - через `json.dumps()`
    - через `json.dump()`
5. Посмотреть на `1.json` **не** в питоне.
Увидеть, что все данные немного отличаются от питоновских (булевы переменные стали с маленькой буквы, `None` превратился в `null`).
_Это связано с тем, что JSON изначально создавался для JavaScript и поэтому имеет такие же названия_.
5. Загрузить `table.csv` из папки w3/ и открыть его в питоне.
Считать содержимое в массив.
Добавить в массив строку из повторяющихся чисел -200 в середину файла и сохранить массив в CSV-файл с именем `middle_row.csv`.
6. Загрузить `table.csv` из папки w3/ и открыть его в питоне.
Считать содержимое в массив.
Добавить колонку (!) с именем `my_col` и значениями на каждом ряду `True`.
Сохранить полученный массив в CSV-файл с именем `new_col.csv`.
7. Создать код, который выбрасывает `ZeroDivisionError`. Обернуть его в `try/except` и вывести "Делим на ноль" в случае деления на ноль.
8. Создать код, который может выбросить `ValueError` (_это может быть попытка привести к `int` "плохую" строку_).
Окружить код `try/except` и добавить `finally` блок, где вывести "Дошел до finally".
Попробовать запустить программу нормально (без выбрасывания исключения) и с исключением.
В обоих случаях должен выполняться код из `finally`.
9. Создать свое исключение (название любое).
Написать код, который выбрасывает его с неким сообщением.
**Не перехватывайте** это исключение в коде - цель задания заключается в том, чтобы увидеть, как он отображается в консоли.
10. Написать код, который вызывает функции в порядке `a() -> b() -> c()`, а в функцию `c` заложите `raise ValueError('my exception')` (_функции `a`, `b`, `c` надо самому объявить_).
Посмотрите на стек-трейс - видно ли, где из трех функций появилась ошибка?
Сделайте скриншот, залейте в репозиторий и будьте готовы ответить на вопросы по чтению stack trace.

**Везде, где требуется написать скрипт или записать результат в файл, нужно залить итоги в GitHub.**
